print("..........................................")
print("TUgas day 1 SISOP kelas B")
print("..........................................")
print("NAMA : Aulia Nur Fitriani")
print("NPM  : 21083010051")
print("..........................................")
print("notes :")
print("..........................................")
print("halo dunia!")
print("ini adaalh skrip bash pertamaku di Linux!")
print("..........................................")
